<template><div class="about-page">
  <div class="about-hero" data-aos="fade-down"><div class="about-avatar">✦</div><h1>关于这个博客</h1><p class="about-tagline">用文字记录思考与成长</p></div>
  <div class="about-content">
    <section class="about-section" data-aos="fade-up"><h2><i class="bi bi-person"></i> 我是谁</h2><p>一名热爱技术的全栈开发者，喜欢探索前沿技术，也享受静下心写代码的时光。</p></section>
    <section class="about-section" data-aos="fade-up" data-aos-delay="100"><h2><i class="bi bi-journal-code"></i> 在这里你会看到</h2><div class="about-topics"><div class="about-topic" v-for="t in topics" :key="t.icon"><i :class="t.icon"></i><strong>{{ t.title }}</strong><span>{{ t.desc }}</span></div></div></section>
    <section class="about-section" data-aos="fade-up" data-aos-delay="200"><h2><i class="bi bi-graph-up"></i> 博客统计</h2><div class="about-stats"><div class="about-stat" v-for="s in statItems" :key="s.label"><div class="stat-num" :ref="el => { if(el) statRefs[s.label] = el }">0</div><div class="stat-label">{{ s.label }}</div></div></div></section>
    <section class="about-section" data-aos="fade-up" data-aos-delay="300"><h2><i class="bi bi-envelope"></i> 联系我</h2><div class="about-links"><a href="mailto:admin@blog.com"><i class="bi bi-envelope-fill"></i> Email</a><a href="#"><i class="bi bi-github"></i> GitHub</a><a href="/rss.xml"><i class="bi bi-rss"></i> RSS</a></div></section>
  </div>
</div></template>

<script setup>
import { ref, reactive, onMounted } from 'vue'; import { postAPI, adminAPI } from '@/api'; import { CountUp } from 'countup.js'
const topics = [{ icon: 'bi bi-laptop', title: '技术笔记', desc: '前端/后端/算法 深度文章' },{ icon: 'bi bi-lightbulb', title: '项目实战', desc: '真实项目的踩坑与经验' },{ icon: 'bi bi-book', title: '读书笔记', desc: '读书心得与精华摘要' },{ icon: 'bi bi-cup-hot', title: '生活随笔', desc: '代码之外的日常思考' }]
const statRefs = reactive({}), statItems = [{ label: '文章', key: 'posts' },{ label: '分类', key: 'categories' },{ label: '标签', key: 'tags' },{ label: '评论', key: 'comments' }]
onMounted(async () => { let p=0,c=0,t=0; try{p=(await postAPI.getPosts({limit:1})).data.total||0}catch(_){} try{c=(await postAPI.getCategories()).data.length}catch(_){} try{t=(await postAPI.getTags()).data.length}catch(_){} const n={posts:p,categories:c,tags:t,comments:c}; setTimeout(()=>{for(const s of statItems){const e=statRefs[s.label];if(e)new CountUp(e,n[s.key],{duration:2}).start()}},300)})
</script>
<style scoped>.about-page{max-width:720px;margin:0 auto;padding:60px 24px 80px}.about-hero{text-align:center;margin-bottom:56px}.about-avatar{width:80px;height:80px;border-radius:50%;background:linear-gradient(135deg,var(--color-accent),var(--color-primary));color:#fff;font-size:2rem;display:inline-flex;align-items:center;justify-content:center;margin-bottom:20px;box-shadow:0 8px 30px rgba(201,169,110,.25)}.about-hero h1{font-size:2rem;font-weight:700;margin:0 0 8px}.about-tagline{font-size:.95rem;color:var(--color-text-muted);margin:0}.about-section{margin-bottom:48px}.about-section h2{font-size:1.15rem;font-weight:700;margin:0 0 16px;display:flex;align-items:center;gap:8px}.about-section h2 i{color:var(--color-accent)}.about-section p{color:var(--color-text-secondary);font-size:.92rem;line-height:1.8;margin:0}.about-topics{display:grid;grid-template-columns:1fr 1fr;gap:16px}@media(max-width:500px){.about-topics{grid-template-columns:1fr}}.about-topic{background:var(--color-surface);border:1px solid var(--color-border-light);border-radius:var(--radius-md);padding:20px;display:flex;flex-direction:column;gap:4px}.about-topic i{font-size:1.3rem;color:var(--color-accent);margin-bottom:4px}.about-topic strong{font-size:.9rem;color:var(--color-text)}.about-topic span{font-size:.8rem;color:var(--color-text-muted)}.about-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}@media(max-width:500px){.about-stats{grid-template-columns:repeat(2,1fr)}}.about-stat{text-align:center;background:var(--color-surface);border:1px solid var(--color-border-light);border-radius:var(--radius-md);padding:20px 12px}.stat-num{font-size:2rem;font-weight:800;color:var(--color-primary);line-height:1}.stat-label{font-size:.78rem;color:var(--color-text-muted);margin-top:6px}.about-links{display:flex;gap:16px;flex-wrap:wrap}.about-links a{display:inline-flex;align-items:center;gap:6px;padding:10px 20px;border-radius:var(--radius-sm);background:var(--color-surface);border:1.5px solid var(--color-border);color:var(--color-text-secondary);text-decoration:none;font-size:.88rem;font-weight:500;transition:all .2s}.about-links a:hover{border-color:var(--color-accent);color:var(--color-primary)}</style>
